### ISSUE TITLE
Hi, why can't I run this code on Android?

### ISSUE THREAD

**Issue by marvin-an** [sterlp/svg2png#12]
I want to run on Android to convert svg to png, so i converted this project to Android Application, however

```
E/MainActivity: null
    Enclosed Exception:
    http://apache.org/xml/features/nonvalidating/load-external-dtd
    org.apache.batik.transcoder.TranscoderException: null
    Enclosed Exception:
    http://apache.org/xml/features/nonvalidating/load-external-dtd
        at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:136)
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:158)
        at Svg2Png.convertFile(Svg2Png.java:85)
        at Svg2Png.convert(Svg2Png.java:34)
        at MainActivity.onCreate$lambda-4(MainActivity.kt:51)
        at MainActivity.$r8$lambda$8aSuWAvfF6SqPdljD478fL8grik(Unknown Source:0)
        at MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7441)
        at android.view.View.performClickInternal(View.java:7418)
        at android.view.View.access$3700(View.java:835)
        at android.view.View$PerformClick.run(View.java:28676)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: org.apache.batik.dom.util.SAXIOException: http://apache.org/xml/features/nonvalidating/load-external-dtd
        at org.apache.batik.dom.util.SAXDocumentFactory.createDocument(SAXDocumentFactory.java:459)
        at org.apache.batik.dom.util.SAXDocumentFactory.createDocument(SAXDocumentFactory.java:357)
        at org.apache.batik.anim.dom.SAXSVGDocumentFactory.createDocument(SAXSVGDocumentFactory.java:203)
        at org.apache.batik.anim.dom.SAXSVGDocumentFactory.createDocument(SAXSVGDocumentFactory.java:283)
        at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:129)
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:158) 
        at Svg2Png.convertFile(Svg2Png.java:85) 
        at Svg2Png.convert(Svg2Png.java:34) 
        at MainActivity.onCreate$lambda-4(MainActivity.kt:51) 
        at MainActivity.$r8$lambda$8aSuWAvfF6SqPdljD478fL8grik(Unknown Source:0) 
        at MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2) 
        at android.view.View.performClick(View.java:7441) 
        at android.view.View.performClickInternal(View.java:7418) 
        at android.view.View.access$3700(View.java:835) 
        at android.view.View$PerformClick.run(View.java:28676) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7842) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
     Caused by: org.xml.sax.SAXNotRecognizedException: http://apache.org/xml/features/nonvalidating/load-external-dtd
        at org.apache.harmony.xml.ExpatReader.setFeature(ExpatReader.java:138)
        at org.apache.batik.dom.util.SAXDocumentFactory.createDocument(SAXDocumentFactory.java:450)
        at org.apache.batik.dom.util.SAXDocumentFactory.createDocument(SAXDocumentFactory.java:357) 
        at org.apache.batik.anim.dom.SAXSVGDocumentFactory.createDocument(SAXSVGDocumentFactory.java:203) 
        at org.apache.batik.anim.dom.SAXSVGDocumentFactory.createDocument(SAXSVGDocumentFactory.java:283) 
        at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:129) 
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:158) 
        at Svg2Png.convertFile(Svg2Png.java:85) 
        at Svg2Png.convert(Svg2Png.java:34) 
        at MainActivity.onCreate$lambda-4(MainActivity.kt:51) 
        at MainActivity.$r8$lambda$8aSuWAvfF6SqPdljD478fL8grik(Unknown Source:0) 
        at MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2) 
        at android.view.View.performClick(View.java:7441) 
        at android.view.View.performClickInternal(View.java:7418) 
        at android.view.View.access$3700(View.java:835) 
        at android.view.View$PerformClick.run(View.java:28676) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7842) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```
Do you know why?

**Comment by sterlp** [comment]
I think the problem is, that Batik SVG Toolkit isn't supported by android because of the Java2D API:
https://stackoverflow.com/questions/7418937/how-to-integrate-batik-with-android-to-open-display-svg-files
