### ISSUE TITLE
The attribute "offset" of the element <stop> is required ***

### ISSUE THREAD

**Issue by c0dehunter** [sterlp/svg2png#4]
Trying to run svg2png on [this svg](https://www.dropbox.com/s/90jac0m24onuvb3/adt.svg?dl=0) produces following error:

```
*** Error: org.apache.batik.transcoder.TranscoderException: null
Enclosed Exception:
file:/C:/Users/One/Desktop/CoinIcons/adt.svg:-1
The attribute "offset" of the element <stop> is required ***
Output Directory: null
```

**Comment by sterlp** [comment]
can't open it, could you please just attach it?

**Comment by TazmanOne** [comment]
Yes, i have same problem.
StackTrace
`The attribute "offset" of the element <stop> is required
        at org.apache.batik.bridge.AbstractSVGGradientElementBridge$SVGStopElementBridge.createStop(Unknown Source)
        at org.apache.batik.bridge.AbstractSVGGradientElementBridge.extractLocalStop(Unknown Source)
        at org.apache.batik.bridge.AbstractSVGGradientElementBridge.extractStop(Unknown Source)
        at org.apache.batik.bridge.AbstractSVGGradientElementBridge.createPaint(Unknown Source)
        at org.apache.batik.bridge.PaintServer.convertURIPaint(Unknown Source)
        at org.apache.batik.bridge.PaintServer.convertPaint(Unknown Source)
        at org.apache.batik.bridge.PaintServer.convertStrokePaint(Unknown Source)
        at org.apache.batik.bridge.PaintServer.convertFillAndStroke(Unknown Source)
        at org.apache.batik.bridge.SVGShapeElementBridge.createShapePainter(Unknown Source)
        at org.apache.batik.bridge.SVGDecoratedShapeElementBridge.createFillStrokePainter(Unknown Source)
        at org.apache.batik.bridge.SVGDecoratedShapeElementBridge.createShapePainter(Unknown Source)
        at org.apache.batik.bridge.SVGShapeElementBridge.buildGraphicsNode(Unknown Source)
        at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(Unknown Source)
        at org.apache.batik.bridge.GVTBuilder.buildComposite(Unknown Source)
        at org.apache.batik.bridge.GVTBuilder.build(Unknown Source)
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(Unknown Source)
        at org.apache.batik.transcoder.image.ImageTranscoder.transcode(Unknown Source)
        at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(Unknown Source)
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(Unknown Source)
        at org.sterl.svg2png.Svg2Png.convertFile(Svg2Png.java:73)
        at org.sterl.svg2png.Svg2Png.convert(Svg2Png.java:40)
        at org.sterl.svg2png.Main.run(Main.java:73)
        at org.sterl.svg2png.Main.main(Main.java:29)`
Error
`*** Error: org.apache.batik.transcoder.TranscoderException: null
Enclosed Exception:
file:/~/progressBar/./ic_ride_inner_progress_blue_inprogress.svg:-1
The attribute "offset" of the element <stop> is required ***
Output Directory: null`

**Comment by sterlp** [comment]
Maybe related to this? https://stackoverflow.com/questions/32957626/element-stop-is-missing-required-attribute-offset-on-svg-linear-gradient-fill
